#!/home/zhangmeng/anaconda3/envs/package_learn/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'mypackage','console_scripts','myscript2'
import re
import sys

# for compatibility with easy_install; see #2198
__requires__ = 'mypackage'

try:
    from importlib.metadata import distribution
except ImportError:
    try:
        from importlib_metadata import distribution
    except ImportError:
        from pkg_resources import load_entry_point


def importlib_load_entry_point(spec, group, name):
    dist_name, _, _ = spec.partition('==')
    print(dist_name)
    matches = (
        entry_point
        for entry_point in distribution(dist_name).entry_points
        if entry_point.group == group and entry_point.name == name
    )
    return next(matches).load()


globals().setdefault('load_entry_point', importlib_load_entry_point)


if __name__ == '__main__':
    print(sys.argv)
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    print(sys.argv)
    sys.exit(load_entry_point('mypackage', 'console_scripts', 'myscript2')())
