#!/home/zhangmeng/anaconda3/envs/package_learn/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'mypackage','console_scripts','myscript2'
import re
import sys
if __name__ == '__main__':
    print(sys.argv)
    print(sys.argv)
